INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Afghanistan','Eastern Mediterranean','Asia',39009447,1);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Albania','Europe','Europe',2877470,2);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Algeria','Africa','Africa',43926079,3);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Andorra','Europe','Europe',77278,4);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Angola','Africa','Africa',32956300,5);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Antigua and Barbuda','Americas','North America',98010,6);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Argentina','Americas','South America',45236884,7);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Armenia','Europe','Asia',2963811,8);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Australia','Western Pacific','Australia/Oceania',25528864,9);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Austria','Europe','Europe',9011577,10);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Azerbaijan','Europe','Asia',10148243,11);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bahamas','Americas','North America',393616,12);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bahrain','Eastern Mediterranean','Asia',1706669,13);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bangladesh','South-East Asia','Asia',164851401,14);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Barbados','Americas','North America',287411,15);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Belarus','Europe','Europe',9449001,16);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Belgium','Europe','Europe',11594739,17);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Belize','Americas','North America',398312,18);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Benin','Africa','Africa',12151976,19);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bhutan','South-East Asia','Asia',772443,20);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bolivia','Americas','South America',11688459,21);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bosnia and Herzegovina','Europe','Europe',3278650,22);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Botswana','Africa','Africa',2356075,23);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Brazil','Americas','South America',212710692,24);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Bulgaria','Europe','Europe',6942854,25);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Burkina Faso','Africa','Africa',20954852,26);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Burma','South-East Asia','Asia',54446389,27);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Burundi','Africa','Africa',11922216,28);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Cabo Verde','Africa','Africa',556581,29);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Cambodia','Western Pacific','Asia',16741375,30);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Cameroon','Africa','Africa',26606188,31);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Canada','Americas','North America',37775022,32);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Central African Republic','Africa','Africa',4837752,33);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Chad','Africa','Africa',16467965,34);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Chile','Americas','South America',19132514,35);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Colombia','Americas','South America',50936262,36);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Comoros','Africa','Africa',871326,37);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Congo','Africa','Africa',5530506,38);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Costa Rica','Americas','North America',5098730,39);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Croatia','Europe','Europe',4102577,40);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Cuba','Americas','North America',11325899,41);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Cyprus','Europe','Asia',1208238,42);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Czechia','Europe','Europe',10711019,43);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Denmark','Europe','Europe',5794279,44);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Djibouti','Eastern Mediterranean','Africa',989387,45);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Dominica','Americas','North America',72004,46);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Dominican Republic','Americas','North America',10858648,47);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Ecuador','Americas','South America',17668824,48);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Egypt','Eastern Mediterranean','Africa',102516525,49);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('El Salvador','Americas','North America',6489514,50);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Equatorial Guinea','Africa','Africa',1407001,51);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Eritrea','Africa','Africa',3551175,52);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Estonia','Europe','Europe',1326627,53);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Eswatini','Africa','Africa',1161348,54);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Ethiopia','Africa','Africa',115223736,55);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Fiji','Western Pacific','Australia/Oceania',897095,56);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Finland','Europe','Europe',5541604,57);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('France','Europe','Europe',65288306,58);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Gabon','Africa','Africa',2230563,59);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Gambia','Africa','Africa',2422754,60);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Georgia','Europe','Asia',3988368,61);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Germany','Europe','Europe',83811260,62);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Ghana','Africa','Africa',31133483,63);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Greece','Europe','Europe',10417673,64);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Greenland','Europe','North America',56780,65);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Grenada','Americas','North America',112576,66);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Guatemala','Americas','North America',17946899,67);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Guinea','Africa','Africa',13164905,68);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Guinea-Bissau','Africa','Africa',1972277,69);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Guyana','Americas','South America',786936,70);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Haiti','Americas','North America',11416103,71);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Holy See','Europe','Europe',801,72);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Honduras','Americas','North America',9919704,73);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Hungary','Europe','Europe',9657785,74);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Iceland','Europe','Europe',341465,75);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('India','South-East Asia','Asia',1381344997,76);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Indonesia','South-East Asia','Asia',273808365,77);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Iran','Eastern Mediterranean','Asia',84097623,78);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Iraq','Eastern Mediterranean','Asia',40306025,79);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Ireland','Europe','Europe',4943200,80);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Israel','Europe','Asia',9197590,81);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Italy','Europe','Europe',60452568,82);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Jamaica','Americas','North America',2962478,83);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Japan','Western Pacific','Asia',126435859,84);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Jordan','Eastern Mediterranean','Asia',10213138,85);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Kazakhstan','Europe','Asia',18798667,86);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Kenya','Africa','Africa',53881160,87);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Kuwait','Eastern Mediterranean','Asia',4276658,88);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Kyrgyzstan','Europe','Asia',6534479,89);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Laos','Western Pacific','Asia',7285750,90);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Latvia','Europe','Europe',1883936,91);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Lebanon','Eastern Mediterranean','Asia',6822220,92);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Lesotho','Africa','Africa',2143943,93);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Liberia','Africa','Africa',5068618,94);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Libya','Eastern Mediterranean','Africa',6880353,95);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Liechtenstein','Europe','Europe',38139,96);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Lithuania','Europe','Europe',2718121,97);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Luxembourg','Europe','Europe',626952,98);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Madagascar','Africa','Africa',27755708,99);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Malawi','Africa','Africa',19174839,100);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Malaysia','Western Pacific','Asia',32406372,101);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Maldives','South-East Asia','Asia',541448,102);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Mali','Africa','Africa',20302901,103);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Malta','Europe','Europe',441663,104);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Mauritania','Africa','Africa',4660728,105);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Mauritius','Africa','Africa',1271985,106);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Mexico','Americas','North America',129066160,107);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Moldova','Europe','Europe',4032983,108);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Monaco','Europe','Europe',39270,109);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Mongolia','Western Pacific','Asia',3283344,110);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Montenegro','Europe','Europe',628074,111);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Morocco','Eastern Mediterranean','Africa',36953359,112);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Mozambique','Africa','Africa',31333962,113);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Namibia','Africa','Africa',2545264,114);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Nepal','South-East Asia','Asia',29186486,115);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Netherlands','Europe','Europe',17138756,116);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('New Zealand','Western Pacific','Australia/Oceania',5002100,117);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Nicaragua','Americas','North America',6632263,118);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Niger','Africa','Africa',24281433,119);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Nigeria','Africa','Africa',206606300,120);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('North Macedonia','Europe','Europe',2083365,121);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Norway','Europe','Europe',5425471,122);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Oman','Eastern Mediterranean','Asia',5118446,123);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Pakistan','Eastern Mediterranean','Asia',221295851,124);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Panama','Americas','North America',4321282,125);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Papua New Guinea','Western Pacific','Australia/Oceania',8963009,126);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Paraguay','Americas','South America',7141091,127);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Peru','Americas','South America',33016319,128);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Philippines','Western Pacific','Asia',109722719,129);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Poland','Europe','Europe',37842302,130);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Portugal','Europe','Europe',10193593,131);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Qatar','Eastern Mediterranean','Asia',2807805,132);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Romania','Europe','Europe',19224023,133);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Russia','Europe','Europe',145940924,134);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Rwanda','Africa','Africa',12981546,135);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Saint Kitts and Nevis','Americas','North America',53237,136);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Saint Lucia','Americas','North America',183712,137);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('San Marino','Europe','Europe',33938,138);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Sao Tome and Principe','Africa','Africa',219544,139);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Saudi Arabia','Eastern Mediterranean','Asia',34865919,140);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Senegal','Africa','Africa',16783877,141);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Serbia','Europe','Europe',8733665,142);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Seychelles','Africa','Africa',98408,143);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Sierra Leone','Africa','Africa',7992169,144);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Singapore','Western Pacific','Asia',5854932,145);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Slovakia','Europe','Europe',5459915,146);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Slovenia','Europe','Europe',2078968,147);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Somalia','Eastern Mediterranean','Africa',15933012,148);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('South Africa','Africa','Africa',59381566,149);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('South Korea','Western Pacific','Asia',51273732,150);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('South Sudan','Africa','Africa',11206572,151);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Spain','Europe','Europe',46756648,152);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Sri Lanka','South-East Asia','Asia',21422362,153);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Sudan','Eastern Mediterranean','Africa',43943536,154);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Suriname','Americas','South America',587154,155);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Sweden','Europe','Europe',10105596,156);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Switzerland','Europe','Europe',8660952,157);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Syria','Eastern Mediterranean','Asia',17539600,158);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Taiwan','Western Pacific','Asia',23821199,159);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Tajikistan','Europe','Asia',9557468,160);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Tanzania','Africa','Africa',59886383,161);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Thailand','South-East Asia','Asia',69817894,162);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Timor-Leste','South-East Asia','Asia',1320812,163);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Togo','Africa','Africa',8296582,164);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Trinidad and Tobago','Americas','North America',1399950,165);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Tunisia','Eastern Mediterranean','Africa',11830801,166);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Turkey','Europe','Asia',84428331,167);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Uganda','Africa','Africa',45867852,168);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Ukraine','Europe','Europe',43705858,169);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Uruguay','Americas','South America',3474956,170);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Uzbekistan','Europe','Asia',33516027,171);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Venezuela','Americas','South America',28427499,172);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Vietnam','Western Pacific','Asia',97425470,173);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Western Sahara','Africa','Africa',598682,174);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Yemen','Eastern Mediterranean','Asia',29886897,175);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Zambia','Africa','Africa',18430129,176);
INSERT INTO country_table(country,who_region,continent,population,country_id) VALUES ('Zimbabwe','Africa','Africa',14883803,177);
